### PR TITLE
Added support for Python2

### PR DESCRIPTION
**Pull request by Nova-Striker**
Imported some modules to make it backward compatible

### CODE REVIEW

**Comment by Mastermind-sap** [comment]
what does these modules do?

**Comment by Nova-Striker** [comment]
> what does these modules do?

In python2 , `print` is a **statement** (not a **function** )so `print "Hello World"` is valid in python2 but `print("Hello World")` is not valid. 
(Vice versa for python3).
To implement `print` as a `function` in python 2 , we have to import `print_function` from `__future__` library.

**Comment by Mastermind-sap** [comment]
ok cool! very informative! :+1:

**Comment by Nova-Striker** [comment]
If you want to know the reason for this transition, see [this](https://stackoverflow.com/questions/6239887/what-is-the-advantage-of-the-new-print-function-in-python-3-x-over-the-python-2)

**Comment by JDeepD** [comment]
> > They have pirated windows most probably
> 
> Doesn't matter

Many reasons. 
Firstly , we dont have admin access. So cant install/update anything without password. 
Secondly, Even on computers which do have installation access, Windows Service packs are outdated. See [this](https://stackoverflow.com/a/33973400/12982627) . Cant update the Windows SPs because again, we need Admin privileges.

**Pull request merged**
