### PR TITLE
Added features

### PR DESCRIPTION
**Pull request by JDeepD**
Added :
- `Pipfile` and `pipfile.lock` to track dependencies.
- Added `requirements.txt` for easy installation of dependencies
- Added `.gitignore`. Ignored `__pycache__`
- Now uses a new dependency : `tabulate`
- A table is created before transaction confirmation

### CODE REVIEW

**Comment by JDeepD** [comment]
Do a squash-merge.

**Comment by Mastermind-sap** [comment]
what is squash merge? and what is piplock? moreover my commits are already merged into the repo

**Comment by JDeepD** [comment]
1. Squash merge merges all intermediate commits into one single commit.
2. Pipfile is a file generated by `pipenv`. Its is a cross between `venv` and `pip`.
3. Your commits are already in this repo, thats why I told to squash merge to prevent same commit messages

**Comment by Mastermind-sap** [comment]
ok @JDeepD

**Comment by subnut** [comment]
@JDeepD has really become a god, it seems.
:bowing_man:

**Comment by JDeepD** [comment]
For me, @subnut  is **GOD**  🤣🤣🤣🤣

**Comment by Mastermind-sap** [comment]
image

**Comment by JDeepD** [comment]
Meanwhile @Mastermind-sap thinking rn
 
Screenshot from 2020-11-23 00-37-38

**Comment by JDeepD** [comment]
Bhai @adnanhasan251  ka Repo whatsapp group ho gaya hai 🤣

**Comment by Mastermind-sap** [comment]
> Meanwhile @Mastermind-sap thinking rn
> 
> Screenshot from 2020-11-23 00-37-38

ha ha ha nice joke😐.....gazab bezatti kr rahe ho meri....thats what a linux user does to a windows user i guess

**Comment by Mastermind-sap** [comment]
> Bhai @adnanhasan251 ka Repo whatsapp group ho gaya hai 🤣

😂😂😂 mei toh wahi bola tha

**Comment by Mastermind-sap** [comment]
image

**Comment by JDeepD** [comment]
> ha ha ha nice joke.....gazab bezatti kr rahe ho meri....thats what a linux user does to a windows user i guess

Meanwhile @subnut : "**Hah noobs. I use Arch btw**"

**Comment by Mastermind-sap** [comment]
> > ha ha ha nice joke.....gazab bezatti kr rahe ho meri....thats what a linux user does to a windows user i guess
> 
> Meanwhile @subnut : "**Hah noobs. I use Arch btw**"

even u use that🙄

**Comment by subnut** [comment]
> Meanwhile @subnut : "Hah noobs. I use Arch btw"

image

**Comment by JDeepD** [comment]
> even u use that

Screenshot from 2020-11-23 01-00-28

**Comment by JDeepD** [comment]
> I **use** Arch, but I **don't know** how to **install** it. I tried about 5 times, but could never get a desktop....
> 
> Whereas @JDeepD has been able to successfully install it, and even got to the desktop, on a **_single_** try.

Wut? No bro. I took me more than a week 🤣

**Comment by JDeepD** [comment]
I always get pass the partition and mounting but cant get pass downloading the dependencies from mirror links specially the one from `iitk`

**Comment by subnut** [comment]
> ha ha ha nice joke.....gazab bezatti kr rahe ho meri....thats what a linux user does to a windows user i guess

Be grateful you're not stuck in linux like I am.

I am now addicted to linux. Even if I want to switch back to Windows, I simply can't.
Why I wanna switch back?
- Audio is garbage (for me, atleast. YMMV)
- No proper replacement for Microsoft Office

**Comment by JDeepD** [comment]
> * Audio is garbage (for me, atleast. YMMV)
> * No proper replacement for Microsoft Office

Prolly the first guy I met who wants to switch back to Windows from Linux

**Comment by JDeepD** [comment]
> I always get pass the partition and mounting but cant get pass downloading the dependencies from mirror links specially the one from `iitk`
```
error : failed retrieving file 'libpulse.....' from mirror.cse.iitk.ac.in : The requested URL returned :404

error : failed retrieving file 'gdm.....' from mirror.cse.iitk.ac.in : The requested URL returned :404

error : failed retrieving file 'networkmanager.....' from mirror.cse.iitk.ac.in : The requested URL returned :404

error : failed retrieving file 'pulseaudio.....' from mirror.cse.iitk.ac.in : The requested URL returned :404
```

**Comment by subnut** [comment]
@JDeepD 
```
sudo reflector --sort score  --save /etc/pacman.d/mirrorlist
```

**Comment by JDeepD** [comment]
But one fine day , I got it downloaded (luckily?)

**Comment by JDeepD** [comment]
> @JDeepD
> 
> ```
> sudo reflector --sort score  --save /etc/pacman.d/mirrorlist
> ```

ya. that solved it. I thought an Indian link would be faster but thats not the case

**Comment by Mastermind-sap** [comment]
Meanwhile github founder: am i a joke to you? I created this platform to share codes and contribute to open source not to chat

**Comment by Mastermind-sap** [comment]
After sometime github official id will also message here

**Comment by JDeepD** [comment]
🤣  Microsoft be like : "*I own a website where people make fun of me*"

**Comment by Mastermind-sap** [comment]
😂😂😂😂

**Comment by JDeepD** [comment]
https://github.com/torvalds/linux

**Comment by subnut** [comment]
Tumlog clash royale khelta hai/tha ?

**Comment by JDeepD** [comment]
@subnut  haa. supercell ka saara game khela hai boom beach ke alava

**Comment by subnut** [comment]
abhi khelta h?

**Comment by JDeepD** [comment]
@subnut  account hai pr khelta nhi

**Comment by Mastermind-sap** [comment]
oo bhai tumlog github se break le liya kya? @JDeepD @subnut  aaj kal koi feed hi nhi aa rha....

**Comment by subnut** [comment]
Nhi toh! Hm toh roz kuch na kuch krte rhta h

Tera feed ko puch, shayad woh GitHub se break le liya 😂

**Comment by Mastermind-sap** [comment]
acha😂

**Comment by Mastermind-sap** [comment]
acha😂

**Comment by JDeepD** [comment]
@subnut  what is the name of this font ?
Screenshot from 2020-11-25 23-50-35

**Comment by subnut** [comment]
Victor Mono

**Comment by JDeepD** [comment]
ok

**Pull request merged**
